# Generated by Django 5.2.4 on 2025-12-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='exam_type',
            field=models.CharField(choices=[('unit', 'Unit Test'), ('half', 'Half-Yearly'), ('pre', 'Pre-Final'), ('mid', 'Mid Exam'), ('semester', 'Semester Exam')], default='unit', max_length=20),
            preserve_default=False,
        ),
    ]
