# Generated by Django 6.0 on 2025-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examination_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('MPC', 'M.P.C'), ('BiPC', 'Bi.P.C'), ('CEC', 'C.E.C'), ('MEC', 'M.E.C'), ('MBiPC', 'M.Bi.P.C'), ('BSc', 'B.Sc'), ('MPCs', 'M.P.Cs'), ('BCom', 'B.Com'), ('BZC', 'B.Z.C')], max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year')], max_length=20),
        ),
    ]
