# Generated by Django 6.0 on 2025-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='popup',
            name='image',
            field=models.ImageField(upload_to='popup/'),
        ),
    ]
